// Code generated by tools/compile-translations.go. DO NOT EDIT.
// source: po/*.po

// Copyright (C) 2020  Matthew "strager" Glazar
// See end of file for extended copyright information.

#include <array>
#include <quick-lint-js/i18n/translation-table.h>

namespace quick_lint_js {
const translation_table translation_data = {
    .mapping_table = translation_table::absolute_mapping_table_from_relative({{
        {0, 0, 0, 0, 0, 0},            //
        {1, 1969, 0, 5228, 0, 8416},   //
        {93, 63, 0, 70, 0, 70},        //
        {18, 13, 0, 16, 0, 16},        //
        {13, 16, 0, 11, 0, 11},        //
        {13, 24, 0, 17, 0, 15},        //
        {15, 14, 0, 13, 0, 13},        //
        {15, 38, 0, 19, 0, 17},        //
        {69, 48, 0, 46, 0, 50},        //
        {83, 55, 3550, 62, 7174, 62},  //
        {32, 32, 57, 34, 45, 38},      //
        {30, 33, 40, 30, 0, 33},       //
        {56, 38, 0, 64, 0, 52},        //
        {23, 15, 0, 19, 0, 18},        //
        {18, 18, 0, 14, 0, 13},        //
        {20, 16, 0, 16, 0, 15},        //
        {0, 0, 0, 23, 0, 19},          //
        {20, 40, 0, 26, 0, 21},        //
        {18, 26, 63, 21, 44, 18},      //
        {36, 32, 52, 35, 42, 36},      //
        {34, 30, 47, 46, 0, 40},       //
        {84, 58, 96, 77, 44, 72},      //
        {46, 18, 26, 39, 18, 24},      //
        {64, 53, 0, 54, 0, 48},        //
        {74, 36, 54, 56, 48, 60},      //
        {55, 81, 72, 73, 57, 55},      //
        {0, 33, 0, 38, 0, 33},         //
        {41, 68, 48, 68, 36, 59},      //
        {25, 46, 25, 27, 22, 23},      //
        {34, 15, 43, 40, 37, 33},      //
        {0, 0, 0, 55, 0, 41},          //
        {57, 72, 67, 22, 46, 19},      //
        {54, 5, 62, 42, 52, 39},       //
        {61, 50, 75, 49, 64, 50},      //
        {69, 23, 79, 41, 51, 48},      //
        {40, 26, 61, 39, 56, 47},      //
        {50, 21, 53, 41, 44, 35},      //
        {48, 27, 44, 37, 43, 36},      //
        {35, 37, 50, 32, 38, 35},      //
        {25, 50, 31, 36, 30, 23},      //
        {36, 12, 51, 38, 37, 36},      //
        {27, 25, 28, 22, 25, 24},      //
        {23, 25, 28, 22, 26, 24},      //
        {19, 19, 20, 26, 15, 18},      //
        {16, 12, 14, 15, 17, 15},      //
        {17, 11, 14, 15, 17, 15},      //
        {31, 12, 34, 35, 33, 29},      //
        {46, 40, 49, 46, 37, 40},      //
        {51, 37, 45, 49, 34, 37},      //
        {37, 22, 52, 37, 37, 40},      //
        {45, 26, 47, 43, 36, 39},      //
        {27, 30, 34, 31, 28, 29},      //
        {98, 37, 86, 82, 0, 77},       //
    }}),

    // clang-format off
    .string_table =
        u8"\0"
        u8"'>' darf nicht direkt in JSX-Text verwendet werden. Anstattdessen {{'>} oder &gt; schreiben.\0"
        u8"do-while-Schleife\0"
        u8"for-Schleife\0"
        u8"if-Anweisung\0"
        u8"while-Schleife\0"
        u8"with-Anweisung\0"
        u8"'{0}' ist f\u00fcr Strings nicht erlaubt. '{1}' anstattdessen verwenden.\0"
        u8"'}' darf nicht direkt in JSX-Text verwendet werden. Anstattdessen {{'}'} schreiben\0"
        u8"BigInt-Literal mit Dezimalpunkt\0"
        u8"BigInt-Literal mit Exponenten\0"
        u8"RegExp-Literale d\u00fcrfen keine Unicode Escapes enthalten\0"
        u8"eine do-While-Schleife\0"
        u8"eine for-Schleife\0"
        u8"eine while-Schleife\0"
        u8"eine with-Anweisung\0"
        u8"eine if-Anweisung\0"
        u8"Bin\u00e4res Zahlenliteral ohne Ziffern\0"
        u8"Ung\u00fcltiges Zeichen in Bezeichner\0"
        u8"Codepunkt innerhalb der Unicode-Escapesequenz darf nicht gr\u00f6\u00dfer als U+10FFFF sein\0"
        u8"Codepunkt au\u00dferhalb des zul\u00e4ssigen Bereichs\0"
        u8"Escape-Zeichen darf nicht nicht in Bezeichnern verwendet werden\0"
        u8"Escape von '-' ist in Tagnamen nicht erlaubt. '-' anstattdessen schreiben\0"
        u8"Hexadezimale Ziffern in Unicode-Escapesequenz erwartet\0"
        u8"Hexadezimales Zahlenliteral ohne Ziffern\0"
        u8"Ung\u00fcltige UTF-8 Sequenz\0"
        u8"Ung\u00fcltige Hex-Escapesequenz: {0}\0"
        u8"Schl\u00fcsselworte d\u00fcrfen keine Escapesequenzen beinhalten\0"
        u8"Veraltete Oktalliterale sind in BigInts nicht erlaubt\0"
        u8"Veraltete Oktalliterale d\u00fcrfen keine Unterstriche enthalten\0"
        u8"Zahlenliteral darf keine aufeinanderfolgenden Unterstriche enthalten\0"
        u8"Zahlenliteral endet mit Unterstrich(en)\0"
        u8"Oktalliterale mit Dezimalpunkt sind nicht erlaubt\0"
        u8"Oktalliterale mit Exponenten sind nicht erlaubt\0"
        u8"Oktales Zahlenliteral ohne Ziffern\0"
        u8"Blockkommentar ohne Ende\0"
        u8"Unbeendete Bezeichner-Escapesequenz\0"
        u8"Unbeendetes RegExp-Literal\0"
        u8"Zeichenkette ohne Ende\0"
        u8"Template ohne Ende\0"
        u8"Unerwartete '#'\0"
        u8"Unerwartetes '@'\0"
        u8"Unerwartetes '\\' in Bezeichner\0"
        u8"Unerwartete Zeichen in bin\u00e4rem Zahlenliteral\0"
        u8"Unerwartete Zeichen in hexadezimalem Zahlenliteral\0"
        u8"Unerwartete Zeichen in Zahlenliteral\0"
        u8"Unerwartete Zeichen in oktalem Zahlenliteral\0"
        u8"Unerwartetes Steuerzeichen\0"
        u8"Die Unicode Bytereihenfolge-Markierung (BOM) darf nicht vor #! zu Beginn eines Skripts erscheinen\0"
        u8"Blockkommentar ohne Beginn\0"
        u8"Facebook says '>' is not allowed; write {{'>'} or &gt; instead\0"
        u8"do-whiley do\0"
        u8"'for' loop \U0001f503\0"
        u8"when (not if) statement\0"
        u8"whenever loop\0"
        u8"what-the-heck-is-wrong-with statement\0"
        u8"smart quotes \U0001f9e0 require the SmartyPantsJS DLC\0"
        u8"Facebook says '}' is not allowed; write {{'}'} instead\0"
        u8"it's Big*Int*, not Big*Decimal*\0"
        u8"BigExponInt is an ES2069 feature\0"
        u8"keep your RegExp flags simple, please\0"
        u8"a do-whiley do\0"
        u8"a 'for' loop \U0001f503\0"
        u8"a whenever loop\0"
        u8"a what-the-heck-is-wrong-with statement\0"
        u8"a when (not if) statement\0"
        u8"binary number lost its genitals\0"
        u8"hold up! \u270b no '{0}' allowed\0"
        u8"U+10FFFF is the limit. what are you trying to accomplish?\0"
        u8"it won't fit \U0001f930\0"
        u8"fugitive \U0001f9b9\u200d\u2642\ufe0f is not allowed in identifiers\0"
        u8"stop being so fancy; just write '-'\0"
        u8"what are you trying to do? This is a Unicode escape sequence, not a Wendy's \U0001f354\0"
        u8"hex number literal has no digits\0"
        u8"this number's too thicc for JavaScript; '{1}' would be used instead\0"
        u8"quick-lint-js only works with nonbinary files\0"
        u8"this ain't hex\0"
        u8"that sequence should escape from this keyword cuz it's not allowed here\0"
        u8"0Ops\0"
        u8"legacy_octal_literals_may_not_contain_underscores\0"
        u8"too__many__underscores\0"
        u8"too_many_underscores_____\0"
        u8"but you said '0o'...\0"
        u8"scientists don't use octal\0"
        u8"<octupus-with-no-legs> has no digits\0"
        u8"you accidentally commented out your whole program\0"
        u8"runaway \\u!\0"
        u8"/unclosed regexp literal\0"
        u8"\"unclosed string literal\0"
        u8"`unclosed template\0"
        u8"#unexpected\0"
        u8"unexp@cted\0"
        u8"unex\\pected\0"
        u8"this number does not identify as binary\0"
        u8"unexpected characters in hex literal\0"
        u8"does not compute \U0001f916\0"
        u8"Cthulhu \U0001f419 is not happy\0"
        u8"you lost control of your code\0"
        u8"your editor BOMd \U0001f4a3 your s#!t \U0001f4a9\0"
        u8"/*\0"
        u8"le lit\u00e9ral BigInt contient un s\u00e9parateur de d\u00e9cimales\0"
        u8"le lit\u00e9ral BigInt contient un exposant\0"
        u8"un litt\u00e9ral RegExp ne peut contenir des \u00e9chappements Unicode\0"
        u8"le litt\u00e9ral num\u00e9rique binaire n'a pas de chiffres\0"
        u8"caract\u00e8re non autoris\u00e9 dans les identifiants\0"
        u8"un point de code dans une s\u00e9quence d'\u00e9chappement Unicode ne peut d\u00e9passer la valeur U+10FFFF\0"
        u8"point de code hors limite\0"
        u8"caract\u00e8re \u00e9chapp\u00e9 non permis dans les identifiants\0"
        u8"nombres hexadecimaux attendus dans une s\u00e9quence d'\u00e9chappement Unicode\0"
        u8"le litt\u00e9ral num\u00e9rique hex n'a pas de chiffres\0"
        u8"s\u00e9quence UTF-8 invalide\0"
        u8"s\u00e9quence d'\u00e9chappement hex invalide: {0}\0"
        u8"les mots-cl\u00e9s ne peuvent pas contenir de s\u00e9quence d'\u00e9chappement\0"
        u8"un litt\u00e9ral octal classique ne peut pas \u00eatre de type BigInt\0"
        u8"un litt\u00e9ral octal classique ne peut pas contenir de tiret de soulignement\0"
        u8"le litt\u00e9ral num\u00e9rique contient plusieurs tirets de soulignement cons\u00e9cutifs\0"
        u8"le litt\u00e9ral num\u00e9rique est suivi d'un tiret de soulignement\0"
        u8"un litt\u00e9ral octal ne peut avoir de partie d\u00e9cimale\0"
        u8"un litt\u00e9ral octal ne peut avoir d'exposant\0"
        u8"le litt\u00e9ral num\u00e9rique octal n'a pas de chiffres\0"
        u8"commentaire de bloc non ferm\u00e9\0"
        u8"s\u00e9quence d'\u00e9chappement d'identifiant non ferm\u00e9e\0"
        u8"litt\u00e9ral regexp non ferm\u00e9\0"
        u8"litt\u00e9ral string non ferm\u00e9\0"
        u8"template non ferm\u00e9\0"
        u8"'#' inattendu\0"
        u8"'@' inattendu\0"
        u8"'\\' inattendu dans un identifiant\0"
        u8"caract\u00e8res inattendus dans un litt\u00e9ral binaire\0"
        u8"caract\u00e8res inattendus dans un litt\u00e9ral hex\0"
        u8"caract\u00e8res inattendus dans un litt\u00e9ral num\u00e9rique\0"
        u8"caract\u00e8res inattendus dans un litt\u00e9ral octal\0"
        u8"caract\u00e8re de contr\u00f4le inattendu\0"
        u8"un indicateur d'ordre des octets (BOM) ne peut figurer avant #! au d\u00e9but d'un script\0"
        u8"commentaire de bloc non ouvert\0"
        u8"'>' n\u00e3o \u00e9 permitido diretamente em um texto JSX; use {{'>'} ou &gt;\0"
        u8"loop 'do-while'\0"
        u8"loop 'for'\0"
        u8"instru\u00e7\u00e3o 'if'\0"
        u8"loop 'while'\0"
        u8"instru\u00e7\u00e3o 'with'\0"
        u8"'{0}' n\u00e3o \u00e9 permitido para strings; use {1}\0"
        u8"'}' n\u00e3o \u00e9 permitido diretamente em um texto JSX; use {{'}'}\0"
        u8"valor BigInt cont\u00e9m casa decimal\0"
        u8"valor BigInt cont\u00e9m expoente\0"
        u8"flags do RegExp n\u00e3o podem conter sequ\u00eancias de escape Unicode\0"
        u8"um loop 'do-while'\0"
        u8"um loop 'for'\0"
        u8"um loop 'while'\0"
        u8"uma instru\u00e7\u00e3o 'with'\0"
        u8"uma instru\u00e7\u00e3o com label\0"
        u8"uma instru\u00e7\u00e3o 'if'\0"
        u8"n\u00famero bin\u00e1rio n\u00e3o tem d\u00edgitos\0"
        u8"caracter n\u00e3o \u00e9 permitido em identificadores\0"
        u8"code point em sequ\u00eancias de escape Unicode n\u00e3o pode ser maior que U+10FFFF\0"
        u8"code point fora do intervalo permitido\0"
        u8"caracter escapado n\u00e3o \u00e9 permiido em identificadores\0"
        u8"escapar '-' n\u00e3o \u00e9 permitido em nomes de tags; use '-'\0"
        u8"d\u00edgitos hexadecimais s\u00e3o esperados em uma sequ\u00eancia de escape Unicode\0"
        u8"n\u00famero hexadecimal n\u00e3o tem d\u00edgitos\0"
        u8"inteiro n\u00e3o pode ser representado e vai ser arredondado para '{1}'\0"
        u8"sequ\u00eancia UTF-8 inv\u00e1lida\0"
        u8"sequ\u00eancia de escape hex inv\u00e1lida: {0}\0"
        u8"palavras-chave n\u00e3o podem conter sequ\u00eancias de escape\0"
        u8"instru\u00e7\u00e3o com label\0"
        u8"n\u00famero octal legado n\u00e3o pode ser BigInt\0"
        u8"n\u00famero octal legado n\u00e3o pode conter underscore\0"
        u8"n\u00famero cont\u00e9m underscores consecutivos\0"
        u8"n\u00famero cont\u00e9m underscore(s) no final\0"
        u8"n\u00famero octal n\u00e3o pode ter casa decimal\0"
        u8"n\u00famero octal n\u00e3o pode ter expoente\0"
        u8"n\u00famero octal n\u00e3o tem d\u00edgitos\0"
        u8"bloco de coment\u00e1rio n\u00e3o encerrado\0"
        u8"sequ\u00eancia de escape n\u00e3o foi fechada\0"
        u8"regexp n\u00e3o encerrado\0"
        u8"string n\u00e3o encerrada\0"
        u8"template n\u00e3o foi fechado\0"
        u8"'#' inesperado\0"
        u8"'@' inesperado\0"
        u8"'\\' inesperado em um identificador\0"
        u8"caracteres inesperados em um n\u00famero bin\u00e1rio\0"
        u8"caracteres inesperados em um n\u00famero hexadecimal\0"
        u8"caracteres inesperados em um n\u00famero\0"
        u8"caracteres inesperados em um n\u00famero octal\0"
        u8"caracter de control inesperado\0"
        u8"unicode byte order mark (BOM) n\u00e3o pode aparecer antes do #! no come\u00e7o do script\0"
        u8"bloco de coment\u00e1rio n\u00e3o foi aberto\0"
        u8"BigInt heltallitter\u00e4r inneh\u00e5ller decimaler\0"
        u8"BigInt heltallitter\u00e4r inneh\u00e5ller exponent\0"
        u8"bin\u00e4ra nummerlitteraler has inga siffror\0"
        u8"tecknet \u00e4r inte till\u00e5tet i indentifierare\0"
        u8"kod punkt ur span\0"
        u8"flykttecken \u00e4r inte till\u00e5tet i indentifierare\0"
        u8"f\u00f6rv\u00e4ntade hexadecimala siffror i Unicode flyktsekvens\0"
        u8"hex nummerlitteral har inga siffror\0"
        u8"ogiltig UTF-8 sekvens\0"
        u8"ogiltig kring\u00e5ende hex sekvens: {0}\0"
        u8"nyckelord kan inte inneh\u00e5lla en flyktsekvens\0"
        u8"\u00e4rftligt octal nummerlitteral kan inte vara BigInt\0"
        u8"\u00e4rftligt octal nummerlitteral kan inte inneh\u00e5lla understr\u00e4ck\0"
        u8"numerlitter\u00e4r inneh\u00e5ller upprepande understr\u00e4ck\0"
        u8"nummerlitter\u00e4r inneh\u00e5ller efterf\u00f6ljande understr\u00e4ck\0"
        u8"oktal nummerlitter\u00e4l kan inte ha decimaler\0"
        u8"oktal nummerlitter\u00e4l kan inte ha exponent\0"
        u8"oktal nummerlitteral har inga siffror\0"
        u8"oavslutad kommentationsstycke\0"
        u8"oavslutad identifierare flyktsekvens\0"
        u8"oavslutad regexplitteral\0"
        u8"oavslutad str\u00e4nglitteral\0"
        u8"oavslutad mall\0"
        u8"of\u00f6rv\u00e4ntad '#'\0"
        u8"of\u00f6rv\u00e4ntad '@'\0"
        u8"of\u00f6rv\u00e4ntad '\\' i identifierare\0"
        u8"of\u00f6rv\u00e4ntat tecken i bin\u00e4rlitteral\0"
        u8"of\u00f6rv\u00e4ntat tecken i hexlitteral\0"
        u8"of\u00f6rv\u00e4ntat tecken i nummerlitteral\0"
        u8"of\u00f6rv\u00e4ntat tecken i oktallitteral\0"
        u8"of\u00f6rv\u00e4ntat kontrolltecken\0"
        u8"unicode byte ordningsm\u00e4rke (BOM) kan inte f\u00f6rekomma f\u00f6re #! i b\u00f6rjan av skript\0"
        u8"'>' is not allowed directly in JSX text; write {{'>'} or &gt; instead\0"
        u8"'do-while' loop\0"
        u8"'for' loop\0"
        u8"'if' statement\0"
        u8"'while' loop\0"
        u8"'with' statement\0"
        u8"'{0}' is not allowed for strings; use {1} instead\0"
        u8"'}' is not allowed directly in JSX text; write {{'}'} instead\0"
        u8"BigInt literal contains decimal point\0"
        u8"BigInt literal contains exponent\0"
        u8"RegExp literal flags cannot contain Unicode escapes\0"
        u8"a 'do-while' loop\0"
        u8"a 'for' loop\0"
        u8"a 'while' loop\0"
        u8"a 'with' statement\0"
        u8"a labelled statement\0"
        u8"an 'if' statement\0"
        u8"binary number literal has no digits\0"
        u8"character is not allowed in identifiers\0"
        u8"code point in Unicode escape sequence must not be greater than U+10FFFF\0"
        u8"code point out of range\0"
        u8"escaped character is not allowed in identifiers\0"
        u8"escaping '-' is not allowed in tag names; write '-' instead\0"
        u8"expected hexadecimal digits in Unicode escape sequence\0"
        u8"hex number literal has no digits\0"
        u8"integer cannot be represented and will be rounded to '{1}'\0"
        u8"invalid UTF-8 sequence\0"
        u8"invalid hex escape sequence: {0}\0"
        u8"keywords cannot contain escape sequences\0"
        u8"labelled statement\0"
        u8"legacy octal literal may not be BigInt\0"
        u8"legacy octal literals may not contain underscores\0"
        u8"number literal contains consecutive underscores\0"
        u8"number literal contains trailing underscore(s)\0"
        u8"octal literal may not have decimal\0"
        u8"octal literal may not have exponent\0"
        u8"octal number literal has no digits\0"
        u8"unclosed block comment\0"
        u8"unclosed identifier escape sequence\0"
        u8"unclosed regexp literal\0"
        u8"unclosed string literal\0"
        u8"unclosed template\0"
        u8"unexpected '#'\0"
        u8"unexpected '@'\0"
        u8"unexpected '\\' in identifier\0"
        u8"unexpected characters in binary literal\0"
        u8"unexpected characters in hex literal\0"
        u8"unexpected characters in number literal\0"
        u8"unexpected characters in octal literal\0"
        u8"unexpected control character\0"
        u8"unicode byte order mark (BOM) cannot appear before #! at beginning of script\0"
        u8"unopened block comment",
    // clang-format on

    .locale_table =
        "de\0"
        "en_US@snarky\0"
        "fr_FR\0"
        "pt_BR\0"
        "sv_SE\0"
        "",
};
}

// quick-lint-js finds bugs in JavaScript programs.
// Copyright (C) 2020  Matthew "strager" Glazar
//
// This file is part of quick-lint-js.
//
// quick-lint-js is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// quick-lint-js is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with quick-lint-js.  If not, see <https://www.gnu.org/licenses/>.
