// Code generated by tools/compile-translations.go. DO NOT EDIT.
// source: po/*.po

// Copyright (C) 2020  Matthew "strager" Glazar
// See end of file for extended copyright information.

#include <quick-lint-js/i18n/translation.h>
#include <quick-lint-js/test-translation-table-generated.h>

namespace quick_lint_js {
// clang-format off
const translated_string test_translation_table[] = {
    {
        "'>' is not allowed directly in JSX text; write {{'>'} or &gt; instead"_translatable,
        {
            u8"'>' is not allowed directly in JSX text; write {{'>'} or &gt; instead",
            u8"'>' darf nicht direkt in JSX-Text verwendet werden. Anstattdessen {{'>} oder &gt; schreiben.",
            u8"Facebook says '>' is not allowed; write {{'>'} or &gt; instead",
            u8"'>' is not allowed directly in JSX text; write {{'>'} or &gt; instead",
            u8"'>' n\u00e3o \u00e9 permitido diretamente em um texto JSX; use {{'>'} ou &gt;",
            u8"'>' is not allowed directly in JSX text; write {{'>'} or &gt; instead",
        },
    },
    {
        "'do-while' loop"_translatable,
        {
            u8"'do-while' loop",
            u8"do-while-Schleife",
            u8"do-whiley do",
            u8"'do-while' loop",
            u8"loop 'do-while'",
            u8"'do-while' loop",
        },
    },
    {
        "'for' loop"_translatable,
        {
            u8"'for' loop",
            u8"for-Schleife",
            u8"'for' loop \U0001f503",
            u8"'for' loop",
            u8"loop 'for'",
            u8"'for' loop",
        },
    },
    {
        "'if' statement"_translatable,
        {
            u8"'if' statement",
            u8"if-Anweisung",
            u8"when (not if) statement",
            u8"'if' statement",
            u8"instru\u00e7\u00e3o 'if'",
            u8"'if' statement",
        },
    },
    {
        "'while' loop"_translatable,
        {
            u8"'while' loop",
            u8"while-Schleife",
            u8"whenever loop",
            u8"'while' loop",
            u8"loop 'while'",
            u8"'while' loop",
        },
    },
    {
        "'with' statement"_translatable,
        {
            u8"'with' statement",
            u8"with-Anweisung",
            u8"what-the-heck-is-wrong-with statement",
            u8"'with' statement",
            u8"instru\u00e7\u00e3o 'with'",
            u8"'with' statement",
        },
    },
    {
        "'{0}' is not allowed for strings; use {1} instead"_translatable,
        {
            u8"'{0}' is not allowed for strings; use {1} instead",
            u8"'{0}' ist f\u00fcr Strings nicht erlaubt. '{1}' anstattdessen verwenden.",
            u8"smart quotes \U0001f9e0 require the SmartyPantsJS DLC",
            u8"'{0}' is not allowed for strings; use {1} instead",
            u8"'{0}' n\u00e3o \u00e9 permitido para strings; use {1}",
            u8"'{0}' is not allowed for strings; use {1} instead",
        },
    },
    {
        "'}' is not allowed directly in JSX text; write {{'}'} instead"_translatable,
        {
            u8"'}' is not allowed directly in JSX text; write {{'}'} instead",
            u8"'}' darf nicht direkt in JSX-Text verwendet werden. Anstattdessen {{'}'} schreiben",
            u8"Facebook says '}' is not allowed; write {{'}'} instead",
            u8"'}' is not allowed directly in JSX text; write {{'}'} instead",
            u8"'}' n\u00e3o \u00e9 permitido diretamente em um texto JSX; use {{'}'}",
            u8"'}' is not allowed directly in JSX text; write {{'}'} instead",
        },
    },
    {
        "BigInt literal contains decimal point"_translatable,
        {
            u8"BigInt literal contains decimal point",
            u8"BigInt-Literal mit Dezimalpunkt",
            u8"it's Big*Int*, not Big*Decimal*",
            u8"le lit\u00e9ral BigInt contient un s\u00e9parateur de d\u00e9cimales",
            u8"valor BigInt cont\u00e9m casa decimal",
            u8"BigInt heltallitter\u00e4r inneh\u00e5ller decimaler",
        },
    },
    {
        "BigInt literal contains exponent"_translatable,
        {
            u8"BigInt literal contains exponent",
            u8"BigInt-Literal mit Exponenten",
            u8"BigExponInt is an ES2069 feature",
            u8"le lit\u00e9ral BigInt contient un exposant",
            u8"valor BigInt cont\u00e9m expoente",
            u8"BigInt heltallitter\u00e4r inneh\u00e5ller exponent",
        },
    },
    {
        "RegExp literal flags cannot contain Unicode escapes"_translatable,
        {
            u8"RegExp literal flags cannot contain Unicode escapes",
            u8"RegExp-Literale d\u00fcrfen keine Unicode Escapes enthalten",
            u8"keep your RegExp flags simple, please",
            u8"un litt\u00e9ral RegExp ne peut contenir des \u00e9chappements Unicode",
            u8"flags do RegExp n\u00e3o podem conter sequ\u00eancias de escape Unicode",
            u8"RegExp literal flags cannot contain Unicode escapes",
        },
    },
    {
        "a 'do-while' loop"_translatable,
        {
            u8"a 'do-while' loop",
            u8"eine do-While-Schleife",
            u8"a do-whiley do",
            u8"a 'do-while' loop",
            u8"um loop 'do-while'",
            u8"a 'do-while' loop",
        },
    },
    {
        "a 'for' loop"_translatable,
        {
            u8"a 'for' loop",
            u8"eine for-Schleife",
            u8"a 'for' loop \U0001f503",
            u8"a 'for' loop",
            u8"um loop 'for'",
            u8"a 'for' loop",
        },
    },
    {
        "a 'while' loop"_translatable,
        {
            u8"a 'while' loop",
            u8"eine while-Schleife",
            u8"a whenever loop",
            u8"a 'while' loop",
            u8"um loop 'while'",
            u8"a 'while' loop",
        },
    },
    {
        "a 'with' statement"_translatable,
        {
            u8"a 'with' statement",
            u8"eine with-Anweisung",
            u8"a what-the-heck-is-wrong-with statement",
            u8"a 'with' statement",
            u8"uma instru\u00e7\u00e3o 'with'",
            u8"a 'with' statement",
        },
    },
    {
        "a labelled statement"_translatable,
        {
            u8"a labelled statement",
            u8"a labelled statement",
            u8"a labelled statement",
            u8"a labelled statement",
            u8"uma instru\u00e7\u00e3o com label",
            u8"a labelled statement",
        },
    },
    {
        "an 'if' statement"_translatable,
        {
            u8"an 'if' statement",
            u8"eine if-Anweisung",
            u8"a when (not if) statement",
            u8"an 'if' statement",
            u8"uma instru\u00e7\u00e3o 'if'",
            u8"an 'if' statement",
        },
    },
    {
        "binary number literal has no digits"_translatable,
        {
            u8"binary number literal has no digits",
            u8"Bin\u00e4res Zahlenliteral ohne Ziffern",
            u8"binary number lost its genitals",
            u8"le litt\u00e9ral num\u00e9rique binaire n'a pas de chiffres",
            u8"n\u00famero bin\u00e1rio n\u00e3o tem d\u00edgitos",
            u8"bin\u00e4ra nummerlitteraler has inga siffror",
        },
    },
    {
        "character is not allowed in identifiers"_translatable,
        {
            u8"character is not allowed in identifiers",
            u8"Ung\u00fcltiges Zeichen in Bezeichner",
            u8"hold up! \u270b no '{0}' allowed",
            u8"caract\u00e8re non autoris\u00e9 dans les identifiants",
            u8"caracter n\u00e3o \u00e9 permitido em identificadores",
            u8"tecknet \u00e4r inte till\u00e5tet i indentifierare",
        },
    },
    {
        "code point in Unicode escape sequence must not be greater than U+10FFFF"_translatable,
        {
            u8"code point in Unicode escape sequence must not be greater than U+10FFFF",
            u8"Codepunkt innerhalb der Unicode-Escapesequenz darf nicht gr\u00f6\u00dfer als U+10FFFF sein",
            u8"U+10FFFF is the limit. what are you trying to accomplish?",
            u8"un point de code dans une s\u00e9quence d'\u00e9chappement Unicode ne peut d\u00e9passer la valeur U+10FFFF",
            u8"code point em sequ\u00eancias de escape Unicode n\u00e3o pode ser maior que U+10FFFF",
            u8"code point in Unicode escape sequence must not be greater than U+10FFFF",
        },
    },
    {
        "code point out of range"_translatable,
        {
            u8"code point out of range",
            u8"Codepunkt au\u00dferhalb des zul\u00e4ssigen Bereichs",
            u8"it won't fit \U0001f930",
            u8"point de code hors limite",
            u8"code point fora do intervalo permitido",
            u8"kod punkt ur span",
        },
    },
    {
        "escaped character is not allowed in identifiers"_translatable,
        {
            u8"escaped character is not allowed in identifiers",
            u8"Escape-Zeichen darf nicht nicht in Bezeichnern verwendet werden",
            u8"fugitive \U0001f9b9\u200d\u2642\ufe0f is not allowed in identifiers",
            u8"caract\u00e8re \u00e9chapp\u00e9 non permis dans les identifiants",
            u8"caracter escapado n\u00e3o \u00e9 permiido em identificadores",
            u8"flykttecken \u00e4r inte till\u00e5tet i indentifierare",
        },
    },
    {
        "escaping '-' is not allowed in tag names; write '-' instead"_translatable,
        {
            u8"escaping '-' is not allowed in tag names; write '-' instead",
            u8"Escape von '-' ist in Tagnamen nicht erlaubt. '-' anstattdessen schreiben",
            u8"stop being so fancy; just write '-'",
            u8"escaping '-' is not allowed in tag names; write '-' instead",
            u8"escapar '-' n\u00e3o \u00e9 permitido em nomes de tags; use '-'",
            u8"escaping '-' is not allowed in tag names; write '-' instead",
        },
    },
    {
        "expected hexadecimal digits in Unicode escape sequence"_translatable,
        {
            u8"expected hexadecimal digits in Unicode escape sequence",
            u8"Hexadezimale Ziffern in Unicode-Escapesequenz erwartet",
            u8"what are you trying to do? This is a Unicode escape sequence, not a Wendy's \U0001f354",
            u8"nombres hexadecimaux attendus dans une s\u00e9quence d'\u00e9chappement Unicode",
            u8"d\u00edgitos hexadecimais s\u00e3o esperados em uma sequ\u00eancia de escape Unicode",
            u8"f\u00f6rv\u00e4ntade hexadecimala siffror i Unicode flyktsekvens",
        },
    },
    {
        "hex number literal has no digits"_translatable,
        {
            u8"hex number literal has no digits",
            u8"Hexadezimales Zahlenliteral ohne Ziffern",
            u8"hex number literal has no digits",
            u8"le litt\u00e9ral num\u00e9rique hex n'a pas de chiffres",
            u8"n\u00famero hexadecimal n\u00e3o tem d\u00edgitos",
            u8"hex nummerlitteral har inga siffror",
        },
    },
    {
        "integer cannot be represented and will be rounded to '{1}'"_translatable,
        {
            u8"integer cannot be represented and will be rounded to '{1}'",
            u8"integer cannot be represented and will be rounded to '{1}'",
            u8"this number's too thicc for JavaScript; '{1}' would be used instead",
            u8"integer cannot be represented and will be rounded to '{1}'",
            u8"inteiro n\u00e3o pode ser representado e vai ser arredondado para '{1}'",
            u8"integer cannot be represented and will be rounded to '{1}'",
        },
    },
    {
        "invalid UTF-8 sequence"_translatable,
        {
            u8"invalid UTF-8 sequence",
            u8"Ung\u00fcltige UTF-8 Sequenz",
            u8"quick-lint-js only works with nonbinary files",
            u8"s\u00e9quence UTF-8 invalide",
            u8"sequ\u00eancia UTF-8 inv\u00e1lida",
            u8"ogiltig UTF-8 sekvens",
        },
    },
    {
        "invalid hex escape sequence: {0}"_translatable,
        {
            u8"invalid hex escape sequence: {0}",
            u8"Ung\u00fcltige Hex-Escapesequenz: {0}",
            u8"this ain't hex",
            u8"s\u00e9quence d'\u00e9chappement hex invalide: {0}",
            u8"sequ\u00eancia de escape hex inv\u00e1lida: {0}",
            u8"ogiltig kring\u00e5ende hex sekvens: {0}",
        },
    },
    {
        "keywords cannot contain escape sequences"_translatable,
        {
            u8"keywords cannot contain escape sequences",
            u8"Schl\u00fcsselworte d\u00fcrfen keine Escapesequenzen beinhalten",
            u8"that sequence should escape from this keyword cuz it's not allowed here",
            u8"les mots-cl\u00e9s ne peuvent pas contenir de s\u00e9quence d'\u00e9chappement",
            u8"palavras-chave n\u00e3o podem conter sequ\u00eancias de escape",
            u8"nyckelord kan inte inneh\u00e5lla en flyktsekvens",
        },
    },
    {
        "labelled statement"_translatable,
        {
            u8"labelled statement",
            u8"labelled statement",
            u8"labelled statement",
            u8"labelled statement",
            u8"instru\u00e7\u00e3o com label",
            u8"labelled statement",
        },
    },
    {
        "legacy octal literal may not be BigInt"_translatable,
        {
            u8"legacy octal literal may not be BigInt",
            u8"Veraltete Oktalliterale sind in BigInts nicht erlaubt",
            u8"0Ops",
            u8"un litt\u00e9ral octal classique ne peut pas \u00eatre de type BigInt",
            u8"n\u00famero octal legado n\u00e3o pode ser BigInt",
            u8"\u00e4rftligt octal nummerlitteral kan inte vara BigInt",
        },
    },
    {
        "legacy octal literals may not contain underscores"_translatable,
        {
            u8"legacy octal literals may not contain underscores",
            u8"Veraltete Oktalliterale d\u00fcrfen keine Unterstriche enthalten",
            u8"legacy_octal_literals_may_not_contain_underscores",
            u8"un litt\u00e9ral octal classique ne peut pas contenir de tiret de soulignement",
            u8"n\u00famero octal legado n\u00e3o pode conter underscore",
            u8"\u00e4rftligt octal nummerlitteral kan inte inneh\u00e5lla understr\u00e4ck",
        },
    },
    {
        "number literal contains consecutive underscores"_translatable,
        {
            u8"number literal contains consecutive underscores",
            u8"Zahlenliteral darf keine aufeinanderfolgenden Unterstriche enthalten",
            u8"too__many__underscores",
            u8"le litt\u00e9ral num\u00e9rique contient plusieurs tirets de soulignement cons\u00e9cutifs",
            u8"n\u00famero cont\u00e9m underscores consecutivos",
            u8"numerlitter\u00e4r inneh\u00e5ller upprepande understr\u00e4ck",
        },
    },
    {
        "number literal contains trailing underscore(s)"_translatable,
        {
            u8"number literal contains trailing underscore(s)",
            u8"Zahlenliteral endet mit Unterstrich(en)",
            u8"too_many_underscores_____",
            u8"le litt\u00e9ral num\u00e9rique est suivi d'un tiret de soulignement",
            u8"n\u00famero cont\u00e9m underscore(s) no final",
            u8"nummerlitter\u00e4r inneh\u00e5ller efterf\u00f6ljande understr\u00e4ck",
        },
    },
    {
        "octal literal may not have decimal"_translatable,
        {
            u8"octal literal may not have decimal",
            u8"Oktalliterale mit Dezimalpunkt sind nicht erlaubt",
            u8"but you said '0o'...",
            u8"un litt\u00e9ral octal ne peut avoir de partie d\u00e9cimale",
            u8"n\u00famero octal n\u00e3o pode ter casa decimal",
            u8"oktal nummerlitter\u00e4l kan inte ha decimaler",
        },
    },
    {
        "octal literal may not have exponent"_translatable,
        {
            u8"octal literal may not have exponent",
            u8"Oktalliterale mit Exponenten sind nicht erlaubt",
            u8"scientists don't use octal",
            u8"un litt\u00e9ral octal ne peut avoir d'exposant",
            u8"n\u00famero octal n\u00e3o pode ter expoente",
            u8"oktal nummerlitter\u00e4l kan inte ha exponent",
        },
    },
    {
        "octal number literal has no digits"_translatable,
        {
            u8"octal number literal has no digits",
            u8"Oktales Zahlenliteral ohne Ziffern",
            u8"<octupus-with-no-legs> has no digits",
            u8"le litt\u00e9ral num\u00e9rique octal n'a pas de chiffres",
            u8"n\u00famero octal n\u00e3o tem d\u00edgitos",
            u8"oktal nummerlitteral har inga siffror",
        },
    },
    {
        "unclosed block comment"_translatable,
        {
            u8"unclosed block comment",
            u8"Blockkommentar ohne Ende",
            u8"you accidentally commented out your whole program",
            u8"commentaire de bloc non ferm\u00e9",
            u8"bloco de coment\u00e1rio n\u00e3o encerrado",
            u8"oavslutad kommentationsstycke",
        },
    },
    {
        "unclosed identifier escape sequence"_translatable,
        {
            u8"unclosed identifier escape sequence",
            u8"Unbeendete Bezeichner-Escapesequenz",
            u8"runaway \\u!",
            u8"s\u00e9quence d'\u00e9chappement d'identifiant non ferm\u00e9e",
            u8"sequ\u00eancia de escape n\u00e3o foi fechada",
            u8"oavslutad identifierare flyktsekvens",
        },
    },
    {
        "unclosed regexp literal"_translatable,
        {
            u8"unclosed regexp literal",
            u8"Unbeendetes RegExp-Literal",
            u8"/unclosed regexp literal",
            u8"litt\u00e9ral regexp non ferm\u00e9",
            u8"regexp n\u00e3o encerrado",
            u8"oavslutad regexplitteral",
        },
    },
    {
        "unclosed string literal"_translatable,
        {
            u8"unclosed string literal",
            u8"Zeichenkette ohne Ende",
            u8"\"unclosed string literal",
            u8"litt\u00e9ral string non ferm\u00e9",
            u8"string n\u00e3o encerrada",
            u8"oavslutad str\u00e4nglitteral",
        },
    },
    {
        "unclosed template"_translatable,
        {
            u8"unclosed template",
            u8"Template ohne Ende",
            u8"`unclosed template",
            u8"template non ferm\u00e9",
            u8"template n\u00e3o foi fechado",
            u8"oavslutad mall",
        },
    },
    {
        "unexpected '#'"_translatable,
        {
            u8"unexpected '#'",
            u8"Unerwartete '#'",
            u8"#unexpected",
            u8"'#' inattendu",
            u8"'#' inesperado",
            u8"of\u00f6rv\u00e4ntad '#'",
        },
    },
    {
        "unexpected '@'"_translatable,
        {
            u8"unexpected '@'",
            u8"Unerwartetes '@'",
            u8"unexp@cted",
            u8"'@' inattendu",
            u8"'@' inesperado",
            u8"of\u00f6rv\u00e4ntad '@'",
        },
    },
    {
        "unexpected '\\' in identifier"_translatable,
        {
            u8"unexpected '\\' in identifier",
            u8"Unerwartetes '\\' in Bezeichner",
            u8"unex\\pected",
            u8"'\\' inattendu dans un identifiant",
            u8"'\\' inesperado em um identificador",
            u8"of\u00f6rv\u00e4ntad '\\' i identifierare",
        },
    },
    {
        "unexpected characters in binary literal"_translatable,
        {
            u8"unexpected characters in binary literal",
            u8"Unerwartete Zeichen in bin\u00e4rem Zahlenliteral",
            u8"this number does not identify as binary",
            u8"caract\u00e8res inattendus dans un litt\u00e9ral binaire",
            u8"caracteres inesperados em um n\u00famero bin\u00e1rio",
            u8"of\u00f6rv\u00e4ntat tecken i bin\u00e4rlitteral",
        },
    },
    {
        "unexpected characters in hex literal"_translatable,
        {
            u8"unexpected characters in hex literal",
            u8"Unerwartete Zeichen in hexadezimalem Zahlenliteral",
            u8"unexpected characters in hex literal",
            u8"caract\u00e8res inattendus dans un litt\u00e9ral hex",
            u8"caracteres inesperados em um n\u00famero hexadecimal",
            u8"of\u00f6rv\u00e4ntat tecken i hexlitteral",
        },
    },
    {
        "unexpected characters in number literal"_translatable,
        {
            u8"unexpected characters in number literal",
            u8"Unerwartete Zeichen in Zahlenliteral",
            u8"does not compute \U0001f916",
            u8"caract\u00e8res inattendus dans un litt\u00e9ral num\u00e9rique",
            u8"caracteres inesperados em um n\u00famero",
            u8"of\u00f6rv\u00e4ntat tecken i nummerlitteral",
        },
    },
    {
        "unexpected characters in octal literal"_translatable,
        {
            u8"unexpected characters in octal literal",
            u8"Unerwartete Zeichen in oktalem Zahlenliteral",
            u8"Cthulhu \U0001f419 is not happy",
            u8"caract\u00e8res inattendus dans un litt\u00e9ral octal",
            u8"caracteres inesperados em um n\u00famero octal",
            u8"of\u00f6rv\u00e4ntat tecken i oktallitteral",
        },
    },
    {
        "unexpected control character"_translatable,
        {
            u8"unexpected control character",
            u8"Unerwartetes Steuerzeichen",
            u8"you lost control of your code",
            u8"caract\u00e8re de contr\u00f4le inattendu",
            u8"caracter de control inesperado",
            u8"of\u00f6rv\u00e4ntat kontrolltecken",
        },
    },
    {
        "unicode byte order mark (BOM) cannot appear before #! at beginning of script"_translatable,
        {
            u8"unicode byte order mark (BOM) cannot appear before #! at beginning of script",
            u8"Die Unicode Bytereihenfolge-Markierung (BOM) darf nicht vor #! zu Beginn eines Skripts erscheinen",
            u8"your editor BOMd \U0001f4a3 your s#!t \U0001f4a9",
            u8"un indicateur d'ordre des octets (BOM) ne peut figurer avant #! au d\u00e9but d'un script",
            u8"unicode byte order mark (BOM) n\u00e3o pode aparecer antes do #! no come\u00e7o do script",
            u8"unicode byte ordningsm\u00e4rke (BOM) kan inte f\u00f6rekomma f\u00f6re #! i b\u00f6rjan av skript",
        },
    },
    {
        "unopened block comment"_translatable,
        {
            u8"unopened block comment",
            u8"Blockkommentar ohne Beginn",
            u8"/*",
            u8"commentaire de bloc non ouvert",
            u8"bloco de coment\u00e1rio n\u00e3o foi aberto",
            u8"unopened block comment",
        },
    },
};
// clang-format on
}

// quick-lint-js finds bugs in JavaScript programs.
// Copyright (C) 2020  Matthew "strager" Glazar
//
// This file is part of quick-lint-js.
//
// quick-lint-js is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// quick-lint-js is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with quick-lint-js.  If not, see <https://www.gnu.org/licenses/>.
